quanti_var = [
    'hospital_number',
    'rectal_temp',
    'pulse',
    'respiratory_rate',
    'nasogastric_reflux_ph',
    'rectal_exam_feces',
    'abdomen',
    'packed_cell_volume',
    'total_protein',
    'abdomo_appearance',
    'abdomo_protein',
    'surgical_lesion',
    'lesion_1',
    'lesion_2',
    'lesion_3',
    'cp_data',
]

quali_var = [
    'surgery',
    'age',
    'temp_of_extremities',
    'peripheral_pulse',
    'mucous_membrane',
    'capillary_refill_time',
    'pain',
    'peristalsis',
    'abdominal_distention',
    'nasogastric_tube',
    'nasogastric_reflux',
]
